networks:
  default: studio-dev
  localnet:
    url: "http://127.0.0.1:4000/api"
    leader_only: false
  studio-dev:
    id: 61997
    url: "https://studio-dev.genlayer.com/api"
    accounts:
      - "0x0000000000000000000000000000000000000000000000000000000000000001"
    chain_type: "studionet"
    leader_only: false

paths:
  contracts: "contracts"
  artifacts: "artifacts"

environment: ".env"
